services:
  # Backend Service
  - type: web
    name: job-tracker-server
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: job-tracker-db
          property: connectionString
      - key: JWT_SECRET
        generate: true

databases:
  # Postgres Database
  - name: job-tracker-db
    plan: free
    databaseName: saas_db
    user: admin

staticSites:
  # Frontend Static Site
  - name: job-tracker-client
    buildCommand: npm install && npm run build
    publishPath: dist
    envVars:
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: job-tracker-server
          property: url
